language: c

addons:
  apt:
    packages:
      - gcc-multilib

env: LIBS="libbsxml-json.a libED_INIFile.a libED_JSONFile.a libED_MATFile.a libED_XLSFile.a libED_XLSXFile.a libED_XMLFile.a libexpat.a libzlib.a"

script:
  - cd ExternData/Resources/C-Sources
  - make CFLAGS="-O3 -msse2 -m32 -fPIC" TARGETDIR="linux32"
  - make CFLAGS="-O3 -fPIC"
  - cd ../Library/linux32
  - tar cJf linux32.tar.xz $LIBS
  - cd ../linux64
  - tar cJf linux64.tar.xz $LIBS
# deployment rules are currently missing but can be added for, e.g, github releases

notifications:
  email: false

sudo: false
